--exclude-from

diff --git a/bin/fe b/bin/fe
--- a/bin/fe
+++ b/bin/fe
@@ -8,6 +8,7 @@ shopt -s lastpipe
 declare -i print_command=0
 declare -i print_command_continue=0
 declare -a user_exclude_dirs=()
+declare -a user_exclude_from=()
 declare -a user_exclude_files=()
 declare -a user_include_files=()
 declare -i emacs=0
@@ -200,6 +201,14 @@ main () {
                 user_exclude_dirs+=(--exclude-dir="${2}")
                 shift 2
                 ;;
+            --exclude-from)
+                if (( $# < 2 )) ; then
+                    echo "fe: option missing required argument - --exclude-from"
+                    exit 1
+                fi
+                user_exclude_from+=(--exclude-from="${2}")
+                shift 2
+                ;;
             --include=*)
                 user_include_files+=(--include="${1#*=}")
                 shift
@@ -212,6 +221,10 @@ main () {
                 user_exclude_dirs+=(--exclude-dir="${1#*=}")
                 shift
                 ;;
+            --exclude-from=*)
+                user_exclude_from+=(--exclude-from="${1#*=}")
+                shift
+                ;;
 
             *)
                 break
@@ -221,6 +234,7 @@ main () {
     declare -a command=(
         "${grep}" -I -r
         "${user_exclude_dirs[@]}"
+        "${user_exclude_from[@]}"
         "${exclude_dirs[@]}"
         "${user_include_files[@]}"
         "${exclude_files[@]}"
